<h2>Numpy</h2><p> numpy is used to create array data structure. it deal only with array and array is faster then list.Numpy is manage ,access array.The time complexity is increased when list is used so we concren Array instead of List in numpy.<br>
# in python no need of similar type of element and it give no error but its not recommended becoz from this the code will be changed so we use similar type of data element<br>
# syntex--int arr[]={};  in this arr mean address of first item</p>

#### Import numpy


In [3]:
import numpy as np
print("numpy is downloaded")

numpy is downloaded


In [3]:
ls=[12,21,23,34,45,56,54,55,67,78,99]
ls

[12, 21, 23, 34, 45, 56, 54, 55, 67, 78, 99]

In [13]:
# print the list as array

ls=[12,21,23,34,45,56,54,55,67,78,99]
arr=np.array(ls)
arr

array([12, 21, 23, 34, 45, 56, 54, 55, 67, 78, 99])

In [15]:
arr.dtype  # return type of array

dtype('int64')

In [16]:
ls=[12,21,23,34,45,56,54,55,67,78,99,12.2]
arr=np.array(ls)
arr
# In the output it include decimal for all the element bcause there are one floating point no in the list 

array([12. , 21. , 23. , 34. , 45. , 56. , 54. , 55. , 67. , 78. , 99. ,
       12.2])

In [17]:
arr.dtype

dtype('float64')

In [18]:
ls=[12,21,23,34,45,56,54,55,67,78,99,12.2,"shalu"]
arr=np.array(ls)
arr
# it convert each and every item in a string

array(['12', '21', '23', '34', '45', '56', '54', '55', '67', '78', '99',
       '12.2', 'shalu'], dtype='<U32')

In [6]:
type(arr)  #ndarray--> n diamentional array

# [1,2,3]   ---> 1d array
# [[],[],[]]  --> 2d array

numpy.ndarray

In [7]:
arr+5   # add 5 in all element

array([ 17,  26,  28,  39,  50,  61,  59,  60,  72,  83, 104])

In [8]:
arr.ndim  #ndim function mean no. of dimension

1

In [19]:
ls=[12,21,23,34,45,56,54,55,67,78,99]
arr=np.array(ls)
arr

array([12, 21, 23, 34, 45, 56, 54, 55, 67, 78, 99])

<h4>Accessing the array element from the index </h4>

In [21]:
a=arr[2]#  first address + (first indexed element * byte of data type  
#ex--  100+(2*4) = 100+8 =108 then jo 108 p element hoga wo print ho jayga)
print(a)  #time comp--o(1)

23


In [22]:
ls=[67,76,77,88,98,90,99,456,54,33]
arr=np.array(ls)
arr

#array cration, item accessing, itemvalue manuplation

array([ 67,  76,  77,  88,  98,  90,  99, 456,  54,  33])

<h4> Accessing--></h4><p>[starting point : stop point : jump point]</p>

In [23]:
arr[2:5:2]   #accessing same as list

array([77, 98])

In [24]:
arr.size    # return the size of the array (as indx no , start from 0)

10

<h4>Length of the array </h4>

In [25]:
len(arr)   #polymorphism 

10

In [30]:
#using python less than 50
for item in ls:
    if item<50 :
        print(item)

33


In [74]:
# using numpy less than 50

arr[arr<50]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [35]:
arr2=np.arange(50)  # arange function  give always 1d array according to the given range
arr2                 # print 50 value included 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

<h4>2D Array Creation </h4><p>(total no of row , total no of columns) </p>

In [38]:
np.ones((10,4))  # create 2d array with random no.
# 10 show raw, 4 show coloumn and print 1 at every place
#np.ones(10).size  # single array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.zeros((10,5))    # create 2d matrix of zero 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
# np.linspace(1,8,5)  # required three arg.
# in between 1 to 8 , give us to 5 item in array
# 1-8 is a range in this and 5 is a no. of element 

np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

<h4>Import random </h4>

In [45]:
import random

In [47]:
#in random module-- randiant function is give random no between the 1 to 10 numbers 
random.randint(1,10)

3

In [48]:
random.random()  # give one random no. 

0.3917441636399822

In [49]:
ls=['eunwoo','jungsook','songkang','woonseok']
ls

['eunwoo', 'jungsook', 'songkang', 'woonseok']

In [53]:
random.choice(ls)  #pick one random name from the list

'woonseok'

In [55]:
random.choices(ls,k=2)  # select two random name from the list. when we need 3 name then we will use k=3

['woonseok', 'jungsook']

In [56]:
ls

['eunwoo', 'jungsook', 'songkang', 'woonseok']

In [57]:
# most used function
random.shuffle(ls)
#position can be changed or not. it used when we need to change position of item or overlap items

In [58]:
ls

['woonseok', 'songkang', 'eunwoo', 'jungsook']

In [59]:
np.random.randint(1,50,23) #random no between 1 to 50 and the no of items is 23 

array([ 7, 36, 10, 37, 12, 21, 16, 16, 27, 12, 21, 29, 20, 43, 22, 48, 40,
       48, 10, 27,  4, 12, 45], dtype=int32)

<h4> For check the version of python</h4>

In [60]:
!python --version

Python 3.12.4


<h4> Random numbers in 2d array</h4>

In [62]:
np.random.randint(0,5,(10,5))  # random value fom 0 to 5 and there are 10 rows and 5 columns

array([[4, 3, 0, 1, 4],
       [2, 1, 3, 4, 0],
       [4, 4, 2, 1, 1],
       [0, 2, 4, 1, 0],
       [1, 1, 4, 3, 4],
       [1, 0, 0, 1, 2],
       [1, 0, 0, 3, 1],
       [4, 1, 0, 2, 1],
       [2, 4, 0, 4, 0],
       [2, 2, 2, 0, 2]], dtype=int32)

In [63]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [66]:
# reshape--> shape can changed .in this code 12 are became row and 5 became col
# for use convert the single array into 2d array
arr.reshape(12,5)

#arr.reshape(10,3,2)   # three dimension

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [68]:
arr2=np.resize(arr,(25,25))
arr2
# it replicate no. when item are more then given values


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 

In [69]:
arr2.shape   # return number of rows and columns

(25, 25)

In [70]:
arr2.ndim    # rerturn the no of dimention

2

In [ ]:
# from reshape 1d is changed into 2d or 3d

In [71]:
arr2.reshape((625,))
# it convert into 1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [72]:
arr2.ravel()  # kitni bhi dimension ka array ho ye use 1d m convert kr deta h
# another type of convert into single array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [73]:
arr2.flatten()  # also convert into 1d array 
# reval or flattern are same

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [4]:
arr=np.random.randint(5,50,24)
arr


array([ 5, 46, 12,  9, 29, 42, 29, 26, 10, 38, 36, 48, 48, 42, 11, 45, 42,
       13, 20, 36, 41, 29, 35,  9], dtype=int32)

In [5]:
arr.min()

np.int32(5)

In [6]:
arr.max()

np.int32(48)

In [7]:
arr.sum()

np.int64(701)

In [9]:
arr=np.random.randint(5,50,(4,3))
arr

array([[20, 42,  6],
       [47, 15,  8],
       [17, 26, 21],
       [12, 43, 37]], dtype=int32)

In [10]:
np.transpose(arr)     # transpose the array . row convert onto columns and col. are convert into row

array([[20, 47, 17, 12],
       [42, 15, 26, 43],
       [ 6,  8, 21, 37]], dtype=int32)

In [12]:
arr.T    #same as transpose

array([[20, 47, 17, 12],
       [42, 15, 26, 43],
       [ 6,  8, 21, 37]], dtype=int32)

In [26]:
arr=np.random.randint(2,12,(10,5))
arr

array([[ 8,  8,  4,  4, 11],
       [ 5,  4, 11,  9,  5],
       [ 4,  9,  5,  2,  2],
       [ 6,  4,  4,  5,  5],
       [ 3,  6, 11,  4,  7],
       [ 7,  3, 10,  2,  6],
       [ 3,  4,  5,  7, 11],
       [ 3, 10,  4,  5,  6],
       [ 4,  2,  4,  2,  2],
       [ 8,  9,  7,  4,  6]], dtype=int32)

In [27]:
arr[-1]   # last raw

array([8, 9, 7, 4, 6], dtype=int32)

In [29]:
# arr[7:10]       # up to last 7 to 10 
arr[7:]               # ese bhi kr skte h end point nhi diya

array([[ 3, 10,  4,  5,  6],
       [ 4,  2,  4,  2,  2],
       [ 8,  9,  7,  4,  6]], dtype=int32)

In [33]:
arr[:,:2]   # two col print

array([[ 8,  8],
       [ 5,  4],
       [ 4,  9],
       [ 6,  4],
       [ 3,  6],
       [ 7,  3],
       [ 3,  4],
       [ 3, 10],
       [ 4,  2],
       [ 8,  9]], dtype=int32)

In [34]:
arr[0 :,:2]

array([[ 8,  8],
       [ 5,  4],
       [ 4,  9],
       [ 6,  4],
       [ 3,  6],
       [ 7,  3],
       [ 3,  4],
       [ 3, 10],
       [ 4,  2],
       [ 8,  9]], dtype=int32)

In [36]:
arr[-10 :,:-3]          #arr[-10:,:2]

array([[ 8,  8],
       [ 5,  4],
       [ 4,  9],
       [ 6,  4],
       [ 3,  6],
       [ 7,  3],
       [ 3,  4],
       [ 3, 10],
       [ 4,  2],
       [ 8,  9]], dtype=int32)

In [39]:
arr[3:6,2:5]

array([[ 4,  5,  5],
       [11,  4,  7],
       [10,  2,  6]], dtype=int32)

In [41]:
arr[0::2,2:]      #[start : stop : jump point]  jump point =2 de to ek ka jump , jump=3 then 2 ka jump.....

array([[ 4,  4, 11],
       [ 5,  2,  2],
       [11,  4,  7],
       [ 5,  7, 11],
       [ 4,  2,  2]], dtype=int32)

In [14]:
arr.ravel()

array([10,  4,  7,  4,  6,  5,  6, 11,  5, 11,  8, 10,  5, 10,  2, 11,  3,
        6,  8,  8,  8,  9,  5,  7,  3,  9, 10,  6,  3,  3,  8,  2,  4, 11,
        5,  6,  6,  6,  9, 11,  7,  4,  7, 10,  7,  5,  4,  8,  7,  9],
      dtype=int32)

In [17]:
arr.reshape(50,)

array([10,  4,  7,  4,  6,  5,  6, 11,  5, 11,  8, 10,  5, 10,  2, 11,  3,
        6,  8,  8,  8,  9,  5,  7,  3,  9, 10,  6,  3,  3,  8,  2,  4, 11,
        5,  6,  6,  6,  9, 11,  7,  4,  7, 10,  7,  5,  4,  8,  7,  9],
      dtype=int32)

In [20]:
arr.resize(50,)
arr

array([10,  4,  7,  4,  6,  5,  6, 11,  5, 11,  8, 10,  5, 10,  2, 11,  3,
        6,  8,  8,  8,  9,  5,  7,  3,  9, 10,  6,  3,  3,  8,  2,  4, 11,
        5,  6,  6,  6,  9, 11,  7,  4,  7, 10,  7,  5,  4,  8,  7,  9],
      dtype=int32)

In [21]:
arr[0]    # 0th raw  now it is in 1d so it show first element

np.int32(10)

<h4># 3D ARRAY:----->>>>>      3D=[2D,2D,2D]</h4>

In [42]:
arr=np.random.randint(2,50,(5,10,5))           # table ,raw ,coloumn
arr                                              # in this 5 table and each table have 10 raw or 5 col

array([[[45, 19,  8, 14, 18],
        [21,  3, 42,  2, 25],
        [37,  9, 45, 19, 16],
        [14, 16, 43, 45, 18],
        [17, 27, 40, 29, 34],
        [34, 24, 45, 40, 42],
        [14, 32, 31, 10, 25],
        [15, 39, 25, 36, 34],
        [15, 31, 18, 48, 19],
        [37, 45, 23,  3, 15]],

       [[34,  2, 29, 48, 15],
        [21, 26, 40, 18, 30],
        [31,  3, 17, 16, 49],
        [25, 14,  2, 21, 49],
        [43, 24, 34,  6, 11],
        [30, 15, 15, 34, 38],
        [11, 45, 15, 34, 18],
        [35, 11, 21, 41, 48],
        [39, 49, 39, 38,  6],
        [26, 20, 49,  8, 20]],

       [[10, 33,  9, 47,  2],
        [ 3, 46, 49,  8,  2],
        [ 2, 27, 11,  4, 32],
        [14, 23, 49, 18, 49],
        [46, 21, 17, 33, 36],
        [11,  9, 13, 47, 49],
        [40, 21, 37, 45, 37],
        [46, 36,  6, 34, 36],
        [41, 29, 22, 20, 44],
        [39, 34, 16, 16,  8]],

       [[37, 31,  7, 18, 29],
        [ 2,  4, 48, 22, 42],
        [37, 20, 49, 34, 13],
    

In [43]:
arr.shape

(5, 10, 5)

In [44]:
arr.ndim

3

In [47]:
arr[0]   # when there is pass single valu then its position table is show
# arr[5]    #show error out of bound index . there are 4 table

array([[45, 19,  8, 14, 18],
       [21,  3, 42,  2, 25],
       [37,  9, 45, 19, 16],
       [14, 16, 43, 45, 18],
       [17, 27, 40, 29, 34],
       [34, 24, 45, 40, 42],
       [14, 32, 31, 10, 25],
       [15, 39, 25, 36, 34],
       [15, 31, 18, 48, 19],
       [37, 45, 23,  3, 15]], dtype=int32)

In [51]:
arr[0,8:,2:]        #3d-- table,raw col
                   # s:e:step,s:e:step

array([[18, 48, 19],
       [23,  3, 15]], dtype=int32)

In [53]:
arr[:,-1:,:]              # for last raw of every table
                          #: for table is show that we dont mention specific table no it take all tables

array([[[37, 45, 23,  3, 15]],

       [[26, 20, 49,  8, 20]],

       [[39, 34, 16, 16,  8]],

       [[ 5, 23, 33, 19, 27]],

       [[33, 19, 14, 27, 24]]], dtype=int32)

In [60]:
arr=np.array([11,2,3])
arr

array([11,  2,  3])

<h4># max()---> it return max element in the array<br>
# argmax()---> it return the index of the max element<br>
#min()----> it return min element<br>
# argmin()---> it return the index of the min element</h4>

In [61]:
arr.max()

np.int64(11)

In [62]:
arr.argmax()

np.int64(0)

In [63]:
arr.sort()
arr

array([ 2,  3, 11])

In [64]:
arr[::-1]      # descending order

array([11,  3,  2])

In [67]:
arr=np.array([1,21,3])
arr

array([ 1, 21,  3])

In [68]:
arr.argsort()   # return index of element of sorted array

array([0, 2, 1])

In [ ]:
# 4d , 5d array also 6d array if possible
# simple operation on matrixes , mean , mode etc

In [69]:
arr=np.random.randint(2,12,(10,5))
arr

array([[10,  4,  7,  8,  4],
       [ 6, 11,  4,  7,  4],
       [ 4,  8,  8,  7,  8],
       [ 7,  4, 11,  2,  9],
       [ 4,  2,  2,  2,  2],
       [ 6, 10, 10,  5,  7],
       [ 7,  6, 10, 11,  7],
       [ 4,  9,  4,  8,  5],
       [ 8,  5,  5,  9,  3],
       [ 4,  6,  3,  7,  9]], dtype=int32)

In [70]:
np.unique(arr) # unique array . no repeated values allow

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [72]:
arr=np.random.randint(2,250,200)
arr

array([  3, 157, 126,  35, 120, 248, 159, 219, 224, 186, 132, 189,  83,
       110,  26,   8,  89, 249, 201, 206, 247,  50, 125, 134, 111, 232,
       233,  10, 216, 135,  46, 148, 100,  78, 219,  39,   6, 198,  52,
       178,  24,  99, 221, 218, 190,  91, 203, 108, 115, 213, 108, 170,
       134,  58,  76, 150, 153, 223, 159,  13, 128, 161,  27, 123, 195,
        44,  12, 130, 101,  58, 161, 222, 212, 222,  45, 133, 174, 220,
         7,  32, 110, 232, 192, 143,   4,  59, 170, 243,  67,  86,  47,
        98,  91, 144,  31, 117,  22, 152, 160, 142, 110, 179,  83, 159,
       210,  29, 212,  58, 142,  89,  25,   4, 243, 112, 222, 107, 173,
        15, 171, 233, 185,  50, 210,  48, 124, 106, 146, 122, 209,  81,
       189, 207, 161, 104, 224,  33,   9, 218, 169,  31,  99, 169, 239,
        50, 181, 175, 242,  30,  97, 135, 103,   4,   7,  26, 224, 182,
       149, 210,   3, 236, 220, 164,  45, 161, 244, 168, 232, 167, 147,
       239,  63, 112,  43,   2, 235, 130, 173,  68, 176,  21, 10

In [73]:
np.mean(arr)  # return the mean fo the array

np.float64(127.435)

In [74]:
np.median(arr)  # return the median of the array

np.float64(131.0)

In [77]:
# np.var(arr)
arr.var()       # return the variance of the array

np.float64(5410.675775)

In [78]:
arr.std()   # standard deviation

np.float64(73.55729586519612)

In [79]:
np.sqrt(25)   # square 

np.float64(5.0)